.github/workflows/lint-pr-title.yml
PR fixes the TODOs by repos being private
Reference: https://github.com/amannn/action-semantic-pull-request/issues/219
N/A
- [ X ] I've reviewed the guidance in CONTRIBUTING.md
=> ci: fix TODOs blocked by repos being private

tests/run.go
Fix the [GitHub issue](https://github.com/runfinch/finch/issues/31) that --pid=host test sometimes fails.
Add a spec for --test=container:<container>.
Tests passed locally.
=> fix: --pid=host tests

run/run_test.go, tests/run.go, tests/tests.go
=> feat: add e2e tests for resource and user flags

run/run_test.go, tests/cp.go, tests/tests.go
Signed-off-by: Mrudul Harwani <mharwani@amazon.com>
runfinch/finch#82
Adding e2e tests for finch cp command
Tests passed locally
=> test: add tests for finch cp

command/command.go, command/get.go, tests/build.go, tests/compose_build.go, tests/compose_logs.go, tests/compose_ps.go, tests/exec.go, tests/image_history.go, tests/image_inspect.go, tests/images.go, tests/inspect.go, tests/network_inspect.go, tests/network_ls.go, tests/network_rm.go, tests/run.go, tests/tag.go, tests/tests.go, tests/volume_inspect.go, tests/volume_ls.go, tests/volume_rm.go
PR renames `StdOut` and `StdErr` to `Stdout` and `Stderr` respectively to make them consistent with the naming in [std lib](https://pkg.go.dev/os#pkg-variables).
=> refactor!: StdOut,StdErr -> Stdout,Stderr

tests/network_create.go, tests/run.go
Currently `run -e/--env` tests don't use the env loop variable, instead they are hardcoded into the test string. We need to use the env loop variable.
=> fix: Fix run -e/--env tests and add missing variable redefinition

tests/run.go
This adds proper tests for the changes to handling of `-e`/`--env` and `--env-file` in runfinch/finch#158
Signed-off-by: Phil Estes <estesp@gmail.com>
=> feat: add additional tests for env vars

run/run_test.go, tests/run.go, tests/tests.go
Signed-off-by: Ziwen Ning <ningziwe@amazon.com>
https://github.com/runfinch/finch/issues/209
Start a server in host and try to curl it from container with `--add-host test-host:host-gateway`
`make run` with the change https://github.com/runfinch/finch/pull/216
- [ X ] I've reviewed the guidance in CONTRIBUTING.md
=> feat: add tests for special IP in --add-host flag

fnet/dial.go, tests/run.go, tests/tests.go
https://github.com/runfinch/finch/issues/196
Use nginx server for testing port publish(`-p/--publish`) flag in the run command instead of [busybox netcat](https://busybox.net/downloads/BusyBox.html#nc). This is due to the fact that the cni gateway in rootful makes a request to the netcat server running in the container and closes the connection which causes netcat to exit before a client on the host can make a connection to it. 
Yes.
=> refactor: Refactor -p/--publish flag test for run command

fnet/dial.go
Code review fix for https://github.com/runfinch/common-tests/pull/39
Yes
=> refactor: specify timeout for HTTP calls in `run -p/--publish` test

tests/exec.go, tests/images.go, tests/run.go
After upgrading `nerdctl` dependency to 1.2.1, [7 e2e tests in finch fail](https://github.com/runfinch/finch/actions/runs/4421068149/jobs/7751480288#step:6:12894) due to failed assertions on output strings of finch commands. 
Output before 1.2.1
```
$ nerdctl images --quiet
69665d02cb32
```
Output in 1.2.1
```
$ nerdctl images --quiet
sha256:ff6bdca1701f3a8a67e328815ff2346b0e4067d32ec36b7992c1fdc001dc8517
```
Output before 1.2.1
```
$ nerdctl run -u nobody:100 alpine id                                   
uid=65534(nobody) gid=100(users)
```
Output in 1.2.1
```
$ nerdctl run -u nobody:100 alpine id
uid=65534(nobody) gid=100(users) groups=100(users)
```
Output before 1.2.1
```
$ nerdctl run -u nobody --group-add 100 alpine id …
```
=> fix: Fix tests to match nerdctl 1.2.1 outputs

tests/compose_down.go
261
Finch Container Development E2E Tests Compose down command fails to delete the volumes due to volume being used by compose up command. This PR added a delay of 10 sec after the compose up command to allow it to fully up and running the service. This additional wait will prevent the error of not being able to delete the volume by compose down command due to concurrent access.
The compose down command fails to delete the volumes because the compose up command is still using them. This PR adds a 10-second delay after the compose up command to avoid the error of not being able to delete the volume by the compose down command due to simultaneous access.
Yes
By submitting this pull request, I confirm that my contribution is …
=> test: fixing e2e test failure due to volume in use error

.github/workflows/ci.yml
Update version of `golangci-lint` to keep it consistent with [finch](https://github.com/runfinch/finch/blob/main/.github/workflows/ci.yaml#L59).
=> ci: Update go linter version

tests/compose_down.go
261
Currently, compose down command sometimes fails due to volume in use by the container. 
example:
```
time="2023-04-11T16:02:03Z" level=warning msg="error while executing [/usr/local/bin/nerdctl volume rm -f finch-compose4020426052_compose_data_volume]: \"time=\\\"2023-04-11T16:02:03Z\\\" level=fatal msg=\\\"volume \\\\\\\"finch-compose4020426052_compose_data_volume\\\\\\\" is in use\\\"\\n\": exit status 1"
```
Yes
=> test: ignore volume in use error during compose down test

go.mod, run/run_test.go, tests/ps.go
Functional test for PS command.
Added functional test for PS command.
Yes.
=> test: Functional test for PS command

tests/inspect.go
verify the result of finch inspect has State.Status and State.Error
https://github.com/runfinch/finch/issues/242
Test for the scenario of the issue
Tested locally.
- [ X ] I've reviewed the guidance in CONTRIBUTING.md
=> feat: verify the result of finch inspect has State.Status and State.Error

fenv/get.go, ffs/create.go, tests/run.go
Test functioning of nested bind mounts with and without $DOCKER_COMAPT set. 
1. Without $FINCH_DOCKER_COMAPT.
```
finch finch run -it  -v /Users/siravara/outer/nest/://Users/siravara/outer/nest/ -v  /Users/siravara/temp_home/:/Users/siravara/outer  public.ecr.aws/amazonlinux/amazonlinux:2 sh -c "ls /Users/siravara/outer/nest/"
finch finch run -it  -v  /Users/siravara/temp_home/:/Users/siravara/outer -v /Users/siravara/outer/nest/://Users/siravara/outer/nest/  public.ecr.aws/amazonlinux/amazonlinux:2 sh -c "ls /Users/siravara/outer/nest/"
```
2. With $FINCH_DOCKER_COMAT set
```
finch finch run -it  -v /Users/siravara/outer/nest/://Users/siravara/outer/nest/ -v  /Users/siravara/temp_home/:/Users/siravara/outer …
```
=> feat: Tests for bind mounts

tests/compose_build.go, tests/cp.go, tests/run.go
nerdctl released v1.5 and we saw some test regressions in runfinch/finch#521:
* compose container suffix changed
* cp now works with stopped containers
* nested bind mounts issue resolved
Follow up PR after in finch to remove `FINCH_DOCKER_COMPAT` env variable: https://github.com/runfinch/finch/issues/418
pulled down runfinch/finch#521 locally, `replace` directive to point to local common-tests, `make test-e2e-container`
=> fix: make tests compatible with nerdctlv1.5

tests/cp.go
N/A
In the `container cp` command test, container path is evaluated using `filepath.Join("/tmp", filename)`. On windows this evaluates to `/tmp\<filename>` which is not a unix path for the container. 
Yes
=> fix: Fix container filepath to make it platform independent

tests/stop.go
Increase acceptable time deviation from 500ms -> 750ms.
This test checks to see that the `-t/--time` flag waits a certain amount of time (in the test's case, 1s) before sending the stop signal and killing the container. We're currently seeing fairly frequent failures of this test in `finch-core`, with stop times very slightly outside of the acceptable range:
- [1.529945577s](https://github.com/runfinch/finch-core/actions/runs/6228992440/job/16933345175?pr=159#step:7:13397)
- [1.528963170s](https://github.com/runfinch/finch-core/actions/runs/6228992440/job/16933345175?pr=159#step:7:13397)
- [1.502652516s](https://github.com/runfinch/finch-core/actions/runs/6228992440/job/16933345175?pr=159#step:7:13314)
- etc...
This exact timing isn't super …
=> fix: increase acceptable time deviation for stop tests with -t

tests/logs.go
Changing values for `--since` and `--until` based on windows e2e testing. For `--since` change from 3s=>5s(for logs to show up) to show logs from [current time - 5s](i.e the container run falls within this window). For `--until`, change from 3s=>5s(for logs not to show up), i.e container start time does not happen between [0 - (current time -5s)]
Yes
=> fix: Update logs test args

command/remove.go
see https://github.com/containerd/nerdctl/commit/0844a51e43df1c7c445c3142e7729069c06812bd
CI was failing in finch and finch-core due to a named volume not getting cleaned up after bumping nerdctl to v1.6.0. turns out there was a change in behavior for the `volume prune` command.
Ran common-tests with @vsiravar and the volume tests succeeded
=> fix: adds --all to the volume prune command to prune named volumes

tests/volume_prune.go
=> fix: add --all to volume prune tests

ffs/create.go, tests/run.go
N/A
Change host paths to windows paths for bind mount tests. 
Yes
=> refactor: refactor bind mount tests for windows

tests/build.go
The following pull request attempts to modify the finch build command to allow the --ssh option.
- https://github.com/runfinch/finch/pull/696
Therefore, this commit adds a test to run finch build with the --ssh option.
Issue #, if available: N/A
*Description of changes:* Details are described in this commit message.
*Testing done:* Yes
=> test: Add a test for --ssh option in finch build command

tests/build.go
Issue #, if available: https://github.com/runfinch/finch/issues/750, https://github.com/runfinch/finch/pull/649/#issuecomment-1879168058
- Disable build --ssh test when running on Windows
- Ran test suite on Windows machine, and it skipped as expected
```
[SKIPPED] non-functional on Windows, see https://github.com/runfinch/finch/issues/750
In [It] at: C:/Users/Administrator/Code/common-tests/tests/build.go:131 @ 01/05/24 20:18:38.223
------------------------------
[SynchronizedAfterSuite]
C:/Users/Administrator/Code/common-tests/run/run_test.go:36
ef5e5b2ec9fd42f39e6c3a3daac04488b0d7c434446b18eaf4c7c7b6e9cc4ea0
ef5e5b2ec9fd42f39e6c3a3daac04488b0d7c434446b18eaf4c7c7b6e9cc4ea0
0a182cb82c93
Untagged: …
```
=> fix: disable build --ssh test on Windows

fnet/dial.go
fix panic in fnet. When HTTP err != nil the test panics due to `err` shadowing the `err` declared outside the for loop. 
Yes. 
=> fix: fix panic in HTTPGetAndAssert

tests/events.go, tests/logs.go
Issue #, if available: Seen several tests fail (especially on Windows) because of these types of checks. See: https://github.com/runfinch/finch/actions/runs/7493150724/job/20398226027 and https://github.com/runfinch/finch/actions/runs/7493200344/job/20398390738
- Adds a timeout and polling to these checks. This should have no impact when the condition is achieved quickly, but allow it to take up to 15 seconds at the worst case
=> fix: allow propagation time for async conditions

tests/run.go
Issue #, if available: Seems like sometimes the nginx pull fails, see https://github.com/runfinch/finch/actions/runs/7506223106/job/20437155927?pr=759
- Increase timeout
=> fix: increase nginx pull timeout

tests/logs.go
Issue #, if available: Still seeing failures: https://github.com/runfinch/finch/actions/runs/7820846068/job/21371714848?pr=795#step:10:6233
- Double event timeout
- The same tests currently runs twice, with different arguments. Sometimes, one of these times succeeds in just under 15 seconds, so increasing the timeout to over 15s may make the test more reliable
- https://github.com/runfinch/finch/actions/runs/7820846068/job/21371714848?pr=795#step:10:6184
=> fix: increase event timeout

tests/events.go, tests/logs.go
Issue #, if available: https://github.com/runfinch/finch/actions/runs/8028176583/job/22044404059?pr=830
Previously, the polling solution would just re-poll with the same string it got from the initial `session.Out.Contents()`, so polling was not really doing anything.
Now, every time it polls, a new value is used.
- Tested locally
=> fix: use new values of session

tests/run.go
=> fix: Add a wait for server to start before doing a curl, to avoid sync issue

tests/tests.go
Issue #, if available: See https://github.com/runfinch/finch/actions/runs/8424406162/job/23068204038?pr=825#step:10:5839
```
time="2024-03-25T17:50:43Z" level=info msg="trying next host" error="failed to do request: Head \"http://localhost:51261/v2/docker/library/alpine/manifests/latest\": dial tcp [::1]:51261: connect: connection refused" host="localhost:51261"
time="2024-03-25T17:50:43Z" level=error msg="server \"localhost:51261\" does not seem to support HTTPS" error="failed to resolve reference \"localhost:51261/docker/library/alpine:latest\": failed to do request: Head \"http://localhost:51261/v2/docker/library/alpine/manifests/latest\": dial tcp [::1]:51261: connect: connection refused"
time="2024-03-25T17:50:43Z" level=info msg="Hint: you may want to try --insecure-registry to …
```
=> fix: track localImages in a new map to enable proper cleanup

tests/compose_logs.go, tests/compose_ps.go, tests/compose_pull.go, tests/tests.go
Issue #, if available: https://github.com/runfinch/finch/actions/runs/8427176493/job/23080891806#step:10:2784
- Fixes issue where some tests were using an uninitialized global variable since the assignment statements were executed before ginkgo's `SynchronizedBeforeSuite`, which actually populates `localImages`
- Somehow I didn't catch this when I did my local testing before the last release, but I have confirmed this change fixes it locally
- Also added a trivial change to allow remote pulls in `SetupLocalRegistry` to take up to 60 seconds
- Local testing
=> fix: use of uninitialized global variable

tests/tests.go
Seems the ecr connection is reset during runtime which restricts any chance for successful pull for open connections. Adding retry to see if that can solve the issue. A more broad approach can to retry the entire process.
=> fix: Retry image pull for 3 times and then fail

tests/tests.go
Add a custom wait logic as the wait for goexec has an assertion, that marks the test fail in case of timeout.
eventually is usually also used with an assertion.
Without the wait logic the retry wont work due to assertion
=> fix: add custom wait for retry logic

tests/events.go, tests/tests.go
This test fails around 50% of time in windows
```
should get real time events from command
```
adding the delay ensures system event process has started before the commands it monitors are running. This is a async call so this fix is required.
- [ x] I've reviewed the guidance in CONTRIBUTING.md
=> fix: add a delay for system event monitoring to start before pull completes as the run commands are async

.github/workflows/release-please.yml
- Follow [migration instructions](https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#migration) from the old release-please since it is now archived
=> ci: migrate release-please action

tests/run.go
Add a test to check for exit code.
Currently for all erroneous exit we exit with exit code 1. With the new approach we would exit with the correct exit code specified in the error. This test is added to validate the change. 
Refer: https://github.com/runfinch/finch/pull/1068
=> feat: Add test to check exit code

tests/exec.go, tests/start.go
This change adds tests that use long form boolean flags with true/false values to verify that the finch command parses and runs the command correctly. 
Verified that the tests pass by running `test-e2e` make target
=> chore: add longform bool flag coverage for e2e testing

.github/workflows/ci.yml, .golangci.yml, command/remove.go, go.mod, tests/build.go, tests/compose_down.go, tests/compose_kill.go, tests/compose_logs.go, tests/cp.go, tests/exec.go, tests/image_history.go, tests/image_prune.go, tests/kill.go, tests/load.go, tests/login.go, tests/logs.go, tests/network_create.go, tests/network_ls.go, tests/ps.go, tests/rm.go, tests/rmi.go, tests/run.go, tests/save.go, tests/start.go, tests/stop.go, tests/volume_ls.go, tests/volume_prune.go
https://github.com/runfinch/common-tests/pull/190 updates ginkgo third-party dependency which comes with Go 1.22 minimum requirements and requires golangci-lint update.
This change updates the golangci-lint version to v1.62.2 and resolves all warnings and errors. This is required to unblock https://github.com/runfinch/common-tests/pull/190
*Testing done:
Lint is successful in CI
=> ci: bump golangci-lint to v1.62.2

tests/image_history.go
#200 
This change adds --no-trunc option for image history tests which expect the full sha256 snapshot ID. Starting in nerdctl 2.0, image history command not specified with no truncation option will display a shorter snapshot ID. This test should continue to work against older Finch versions which have support for --no-trunc option.
```
austin@nimbus:~/workspace/nerdctl$ nerdctl image history --format "{{.Snapshot}}" alpine:3.19
<missing>
sha256:ba79b2c0127890636a791eb3ec3993cce08a5…
```
Ran test in https://github.com/runfinch/finch-core/pull/472
=> feat: specify no-trunc for full snapshot ID

tests/compose_down.go, tests/compose_kill.go, tests/compose_logs.go
#202, #206
This change adds a sigterm handler to compose services to efficiently allow compose down to cleanup. This change also reworks `compose kill --signal` test such that the services are stopped when sending SIGTERM to be more aligned with the commands functionality.
Ran test in https://github.com/runfinch/finch-core/pull/472
=> fix: add sigterm handler to compose services

option/modifier.go, option/option.go, tests/compose_build.go
Resolves https://github.com/runfinch/common-tests/issues/209
finch-core currently uses limactl shell + nerdctl to test macOS VM image and container runtime archive updates. Currently there is no simple solution for passing through environment variables which is required for compose build test suite. This is currently blocking common-tests updates in finch-core.
This change adds features map to option for skipping unsupported tests based on supported features.
=> feat: add option features to skip tests

tests/builder_prune.go
#196
This change adds -f flag to builder prune for no prompt confirmation.
Ran test in https://github.com/runfinch/finch-core/pull/472
=> feat: specify builder prune -f for no prompt

tests/volume_create.go
#198 
This change tests that volume creation is idempotent. Before the behavior was to fail with exit code 1; however, starting with nerdctl 2.0 the expected behavior is to warn users and continue with no error.
Ran test in https://github.com/runfinch/finch-core/pull/472
=> feat: create volume command should be idempotent

option/modifier.go, option/nerdctl.go, option/option.go, option/option_test.go, tests/builder_prune.go, tests/volume_create.go
nerdctl v2 rollout is quick for macOS and Windows, but slow for Linux (~weeks).
This change enables test runners to specify the nerdctl version depending on the runtime for that platform and tests will run accordingly.
Ran in https://github.com/runfinch/finch/pull/1237
=> fix: make tests backwards compatible with nerdctl v1

tests/builder_prune.go, tests/tests.go
Fix test to check buildkit cache is cleared on prune
Tested locally to confirm builder prune is able to remove dangling build cache.
=> fix: buildkit cache prune
